# Generated by Django 3.2 on 2021-05-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210503_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='isDone',
            new_name='is_done',
        ),
    ]
