# Generated by Django 3.2 on 2021-05-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0007_photo_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='owner',
        ),
        migrations.AddField(
            model_name='week',
            name='owner_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
