# Generated by Django 3.2 on 2021-05-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210510_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='has_been_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
