# Generated by Django 3.2 on 2021-05-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_swap_has_been_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='users',
        ),
    ]
