# Generated by Django 3.2 on 2021-05-10 14:09

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_week_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
