# Generated by Django 3.2 on 2021-05-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_swap_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='created',
        ),
    ]
