# Generated by Django 3.2 on 2021-05-10 15:10

from django.db import migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'admin'),
        Group(name=u'member'),
        Group(name=u'Hammy'),
        Group(name=u'Toby'),
        Group(name=u'Connie'),
        Group(name=u'Cherie'),
        Group(name=u'Tom'),
        Group(name=u'Chris'),
    ])

    

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_swap_created'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]

